Repository Tatii22/Car-Dealer-App-UI-Design, pull requests merged in 2025-08, with the labels that each got.

#19 :sparkles: feat: Se crea html para sign in
  SRC/sign in.html
  img/Logo Facebook.svg
  img/Logo Google.svg
  img/or.svg
  img/verocultar.svg
Labels: Maquetacion

#20 Estructuración pagina principal
  SRC/main.html
  img/Vector.svg
  img/branchs/BMW.svg
  img/branchs/Lamborghini.svg
  img/branchs/Mercedes Benz.svg
  img/branchs/Volvo.svg
  img/car-cards/BMW-X1.svg
  img/car-cards/ICON/icon (1).svg
  img/car-cards/ICON/icon.svg
  img/car-cards/ICON/rayo.svg
  img/car-cards/ICON/recomended.svg
  img/menu-close.png
  img/siderbar/Line.svg
  img/siderbar/auto.svg
  img/siderbar/bolsa.svg
  img/siderbar/config.svg
  img/siderbar/dashboard icon.svg
  img/siderbar/logo.svg
  img/siderbar/tijera.svg
  img/siderbar/volante.svg
  img/top/Ellipse 16.png
  img/top/Ellipse noti.png
  img/top/Rectangle 2.svg
  img/top/campana.png
  img/top/dimensions.png
  img/top/lupa.png
  img/top/profile.png
Labels: Maquetacion

#21 2 diseño de pagina de sign in
  CSS/sign-in.css
  SRC/sign in.html
  img/img sign in/Logo Facebook.svg
  img/img sign in/Logo Google.svg
  img/img sign in/carro login.png
  img/img sign in/or.svg
  img/img sign in/verocultar.svg
Labels: Diseño

#25 Diseño pagina principal #1
  CSS/main.css
  CSS/menu/main.css
  SRC/main.html
  Sounds/Yofukashi no Uta Season 2 Opening Full _ Mirage - Sub. Español ♡.mp3
  img/car-cards/Jeep Rubicon.png
  img/car-cards/Lamborghini Urus.png
  img/car-cards/Lamborghini Urus.svg
  img/car-cards/Mercedes-Benz AMG G 63.png
  img/car-cards/Porsche 911.png
  img/car-cards/Volvo XC90.png
Labels: Diseño

#27 Estructura pagina
  CSS/sign-in.css
  CSS/sign-up.css
  CSS/structura.css
  SRC/sign in.html
  SRC/sign up.html
  SRC/structura.html
Labels: Maquetacion, Diseño

#28 17 estructuración pagina settings
  CSS/settings.css
  SRC/main.html
  SRC/settings.html
  img/icons settings/casa.svg
  img/icons settings/email.svg
  img/icons settings/genero.svg
  img/icons settings/pastel.svg
Labels: Maquetacion

#29 7 estructuración pagina assets
  CSS/assets.css
  SRC/assets.html
  img/assets/calendar 1.svg
  img/assets/car 1.svg
  img/assets/car-sideview 1.svg
  img/assets/car1.png
  img/assets/car2.png
  img/assets/car3.png
  img/assets/car4.png
  img/assets/car5.png
  img/assets/car6.png
  img/assets/car7.png
  img/assets/car8.png
  img/assets/carrera.svg
  img/assets/carro-amarillo.png
  img/assets/flash-filled 1.svg
  img/assets/gasolina.svg
  img/assets/ramas.svg
  img/assets/user.png
  img/assets/🦆 icon _dollar circle_.svg
  img/assets/🦆 icon _location pin_.svg
Labels: Maquetacion

#31 Estructuración pagina booking
  SRC/Booking.html
  img/car-cards/BMW-M5.png
  img/car-cards/ICON/icon (1).svg
  img/car-cards/ICON/icon.png
  img/car-cards/ICON/icon.svg
  img/car-cards/ICON/rayo.svg
  img/car-cards/ICON/settings.svg
  img/car-cards/ICON/shared.svg
  img/car-cards/Lamborghini Aventador.png
  img/car-cards/Mercedes Benz.png
Labels: Maquetacion

#32 13 estructuración pagina sell cars
  CSS/sell-cars.css
  SRC/sell-cars.html
  img/sell-cars/button.svg
  img/sell-cars/capas.png
  img/sell-cars/car.svg
  img/sell-cars/carrito.png
  img/sell-cars/dato1.svg
  img/sell-cars/dato2.svg
  img/sell-cars/dato3.svg
  img/sell-cars/peso.svg
  img/sell-cars/share.svg
Labels: Maquetacion

#33 10 pagina assets
  CSS/assets.css
  SRC/assets.html
  img/assets/alternate-phone 1.svg
  img/assets/mail 1.svg
Labels: Diseño

#35 14 pagina sell cars
  CSS/sell-cars.css
  SRC/sell-cars.html
Labels: Diseño
